from jaloneditinterface import IBlocPresentation
from jaloneditinterface import IGlossaire
from jaloneditinterface import IBibliographie
from jaloneditinterface import IDocumentSemantique
from jaloneditinterface import IVideo